export type Item = {id:string;name:string;name_ar?:string;description?:string;description_ar?:string;image?:string;category?:string;benefits?:string;benefits_ar?:string;related?:string;related_ar?:string;qualification?:string;qualification_ar?:string;specialization?:string;specialization_ar?:string;experience?:string;experience_ar?:string;expertise?:string;expertise_ar?:string;price?:string;price_ar?:string;included?:string;included_ar?:string;highlights?:string;highlights_ar?:string;order?:string};
export type Content = {welcome:Record<string,string>;about:Record<string,string>;contact:Record<string,string>;categories:Item[];services:Item[];doctors:Item[];packages:Item[];banners:Item[]};
export const initialContent:Content={
 welcome:{video_url:'/media/clinic-intro.mp4',language_video_url:'/media/language-intro.mp4',title:'Advanced Dermatology.\nPersonalized Care.',title_ar:'طب جلدية متقدم.\nرعاية شخصية.',description:'Explore dermatology, aesthetic, laser and hair treatments — with care centered around you.',description_ar:'اكتشف علاجات الجلدية والتجميل والليزر والشعر — برعاية تتمحور حول احتياجاتك.'},
 about:{overview:'Dr. Ashish Bhola Dermatology Center brings together dermatology, facial aesthetics, advanced skin treatments and laser technologies in Doha. Established in 2018, the clinic is led by Dr. Ashish Bhola.',overview_ar:'يجمع مركز د. أشيش بهولا للأمراض الجلدية في الدوحة بين طب الجلدية وتجميل الوجه وعلاجات البشرة المتقدمة وتقنيات الليزر. تأسس المركز عام 2018 ويقوده د. أشيش بهولا.',profile:'A personalized approach to skin health and aesthetic care.',profile_ar:'نهج شخصي لصحة البشرة والرعاية التجميلية.',vision:'',vision_ar:'',mission:'',mission_ar:'',aim:'',aim_ar:'',whyChoose:'Specialist-led care, personalized treatment planning and advanced technology.',whyChoose_ar:'رعاية بإشراف اختصاصي، وخطط علاج شخصية وتقنيات متقدمة.',technology:'Explore our laser treatments and advanced devices.',technology_ar:'اكتشف علاجات الليزر والأجهزة المتقدمة لدينا.',patientCare:'Speak with our clinical team about the care that is right for you.',patientCare_ar:'تحدث مع فريقنا الطبي لمعرفة الرعاية المناسبة لك.'},
 contact:{address:'Villa 32, Zone 55, Street 120, P.O. Box 90789, Doha, Qatar',address_ar:'فيلا 32، المنطقة 55، شارع 120، ص.ب 90789، الدوحة، قطر',telephone:'+974 4483 7373',telephone_ar:'+974 4483 7373',telephone2:'+974 4417 7373',telephone2_ar:'+974 4417 7373',mobile:'+974 5080 4545',mobile_ar:'+974 5080 4545',email:'',email_ar:'',hours:'',hours_ar:'',instagram:'https://www.instagram.com/dr.ashishbholaclinic/',facebook:'',tiktok:'',map:'https://www.google.com/maps/search/?api=1&query=Dr.+Ashish+Bhola+Dermatology+Center+Doha'},
 categories:[
  {id:'facial',name:'Facial & Aesthetic',name_ar:'الوجه والتجميل',description:'Glow, lift & rejuvenation',description_ar:'إشراقة وشد وتجديد',image:'/media/image26.webp',order:'1'},
  {id:'skin',name:'Advanced Skin Therapies',name_ar:'علاجات البشرة المتقدمة',description:'Renewal & repair',description_ar:'تجديد وإصلاح',image:'/media/image27.webp',order:'2'},
  {id:'laser',name:'Laser Treatments',name_ar:'علاجات الليزر',description:'Precision & technology',description_ar:'دقة وتقنية متقدمة',image:'/media/image28.webp',order:'3'},
  {id:'devices',name:'Advanced Devices',name_ar:'الأجهزة المتقدمة',description:'Innovation in skin care',description_ar:'ابتكار في العناية بالبشرة',image:'/media/image29.webp',order:'4'},
  {id:'hair',name:'Hair Treatments',name_ar:'علاجات الشعر',description:'Regrowth & restoration',description_ar:'استعادة ونمو الشعر',image:'/media/image30.webp',order:'5'}
 ],
 services:[
  {id:'hydrafacial',name:'Hydrafacial',name_ar:'هيدرافيشل',category:'facial',image:'/media/image42.png',description:'A multi-step treatment that cleanses, exfoliates, extracts and hydrates the skin for a refreshed glow.',description_ar:'علاج متعدد الخطوات ينظف البشرة ويقشرها ويزيل الشوائب ويرطبها لمنحها إشراقة وانتعاشاً.',benefits:'Deep cleansing\nHydration\nSkin brightening\nImproved texture',benefits_ar:'تنظيف عميق\nترطيب\nإشراقة البشرة\nتحسين ملمس البشرة',related:'Chemical Peels, Medical-Grade Facials',related_ar:'التقشير الكيميائي، علاجات الوجه الطبية'},
  {id:'facial-0',name:'Botox & Dermal Fillers',name_ar:'البوتوكس والفيلر',category:'facial',image:'/media/image34.webp',description:'Refine and restore volume.',description_ar:'تحسين الملامح واستعادة الحجم.',related_ar:''},
  {id:'facial-1',name:'Chemical Peels',name_ar:'التقشير الكيميائي',category:'facial',image:'/media/image35.webp',description:'Resurface and brighten.',description_ar:'تجديد سطح البشرة وإضفاء الإشراقة.',related_ar:''},
  {id:'facial-2',name:'Medical-Grade Facials',name_ar:'علاجات الوجه الطبية',category:'facial',image:'/media/image36.webp',description:'Customized skin therapy.',description_ar:'عناية مخصصة للبشرة.',related_ar:''},
  {id:'facial-3',name:'Facial Mapping',name_ar:'تحليل وتخطيط الوجه',category:'facial',image:'/media/image37.webp',description:'Skin assessment and planning.',description_ar:'تقييم البشرة ووضع خطة مناسبة.',related_ar:''},
  {id:'facial-4',name:'Non-Surgical Face Lift',name_ar:'شد الوجه غير الجراحي',category:'facial',image:'/media/image38.webp',description:'Explore lift and contour treatments.',description_ar:'اكتشف علاجات الشد وتحسين تحديد الملامح.',related_ar:''}
 ],
 doctors:[{id:'ashish',name:'Dr. Ashish Bhola',name_ar:'د. أشيش بهولا',image:'/media/image44.png',qualification:'Specialist Dermatologist',qualification_ar:'اختصاصي أمراض جلدية',specialization:'Owner & Medical Director',specialization_ar:'المالك والمدير الطبي',experience:'23+',experience_ar:'23+',description:'Dr. Ashish Bhola leads the clinic with a personalized approach to dermatology, facial aesthetics, advanced skin treatments and laser technologies.',description_ar:'يقود د. أشيش بهولا المركز بنهج شخصي في طب الجلدية وتجميل الوجه وعلاجات البشرة المتقدمة وتقنيات الليزر.',expertise:'Dermatology\nFacial Aesthetics\nAdvanced Skin Treatments\nLaser Technologies',expertise_ar:'طب الجلدية\nتجميل الوجه\nعلاجات البشرة المتقدمة\nتقنيات الليزر'}],
 packages:[],
 banners:[{id:'welcome',name:'Personalized skin care',name_ar:'عناية شخصية بالبشرة',image:'/media/image42.png'}]
};
